import json
import os

TARIFF_DATA = [
    # General Surgery
    {"package_code": "SG013", "procedure_code": "SG013A", "package_name": "Appendectomy", "procedure_name": "Laparoscopic Appendectomy", "price": 22000.0, "ceiling_inr": 22000.0, "speciality": "General Surgery", "linked_icd10": "K35.80", "pre_auth_required": True, "mandatory_investigations": ["USG Abdomen", "CBC", "Histopathology Report"]},
    {"package_code": "SG013", "procedure_code": "SG013B", "package_name": "Appendectomy", "procedure_name": "Open Appendectomy", "price": 17000.0, "ceiling_inr": 17000.0, "speciality": "General Surgery", "linked_icd10": "K35.80", "pre_auth_required": False, "mandatory_investigations": ["USG Abdomen", "CBC", "Histopathology Report"]},
    {"package_code": "SG001", "procedure_code": "SG001A", "package_name": "Cholecystectomy", "procedure_name": "Laparoscopic Cholecystectomy", "price": 28000.0, "ceiling_inr": 28000.0, "speciality": "General Surgery", "linked_icd10": "K80.20", "pre_auth_required": True, "mandatory_investigations": ["USG Whole Abdomen", "LFT", "Histopathology Report"]},
    {"package_code": "SG001", "procedure_code": "SG001B", "package_name": "Cholecystectomy", "procedure_name": "Open Cholecystectomy", "price": 21000.0, "ceiling_inr": 21000.0, "speciality": "General Surgery", "linked_icd10": "K80.20", "pre_auth_required": False, "mandatory_investigations": ["USG Whole Abdomen", "LFT", "Histopathology Report"]},
    {"package_code": "SG004", "procedure_code": "SG004A", "package_name": "Inguinal Hernia Repair", "procedure_name": "Unilateral Open Inguinal Hernioplasty", "price": 18000.0, "ceiling_inr": 18000.0, "speciality": "General Surgery", "linked_icd10": "K40.90", "pre_auth_required": False, "mandatory_investigations": ["USG Inguinoscrotal", "Clinical Photograph"]},
    {"package_code": "SG004", "procedure_code": "SG004B", "package_name": "Inguinal Hernia Repair", "procedure_name": "Bilateral Laparoscopic Hernioplasty", "price": 32000.0, "ceiling_inr": 32000.0, "speciality": "General Surgery", "linked_icd10": "K40.90", "pre_auth_required": True, "mandatory_investigations": ["USG Inguinoscrotal", "Clinical Photograph"]},
    {"package_code": "SG007", "procedure_code": "SG007A", "package_name": "Hemorrhoidectomy", "procedure_name": "Stapled Anopexy / Hemorrhoidectomy", "price": 19500.0, "ceiling_inr": 19500.0, "speciality": "General Surgery", "linked_icd10": "K64.9", "pre_auth_required": False, "mandatory_investigations": ["Proctoscopy Report", "CBC"]},

    # Orthopaedics
    {"package_code": "OR001", "procedure_code": "OR001A", "package_name": "Total Knee Replacement", "procedure_name": "Unilateral Total Knee Arthroplasty (TKR)", "price": 85000.0, "ceiling_inr": 85000.0, "speciality": "Orthopaedics", "linked_icd10": "M17.11", "pre_auth_required": True, "mandatory_investigations": ["X-Ray Both Knees AP/Lateral Weight Bearing", "Implant Invoice with Barcode"]},
    {"package_code": "OR001", "procedure_code": "OR001B", "package_name": "Total Knee Replacement", "procedure_name": "Bilateral Total Knee Arthroplasty (TKR)", "price": 150000.0, "ceiling_inr": 150000.0, "speciality": "Orthopaedics", "linked_icd10": "M17.0", "pre_auth_required": True, "mandatory_investigations": ["X-Ray Both Knees AP/Lateral Weight Bearing", "Implant Invoice with Barcode"]},
    {"package_code": "OR003", "procedure_code": "OR003A", "package_name": "Total Hip Replacement", "procedure_name": "Cemented Total Hip Replacement (THR)", "price": 75000.0, "ceiling_inr": 75000.0, "speciality": "Orthopaedics", "linked_icd10": "M16.11", "pre_auth_required": True, "mandatory_investigations": ["Pelvis with Both Hips AP X-Ray", "Pre-op & Post-op X-Ray"]},
    {"package_code": "OR003", "procedure_code": "OR003B", "package_name": "Total Hip Replacement", "procedure_name": "Uncemented Total Hip Replacement (THR)", "price": 95000.0, "ceiling_inr": 95000.0, "speciality": "Orthopaedics", "linked_icd10": "M16.11", "pre_auth_required": True, "mandatory_investigations": ["Pelvis with Both Hips AP X-Ray", "Pre-op & Post-op X-Ray"]},
    {"package_code": "OR012", "procedure_code": "OR012A", "package_name": "Fracture Fixation", "procedure_name": "Open Reduction Internal Fixation (ORIF) Femur", "price": 30000.0, "ceiling_inr": 30000.0, "speciality": "Orthopaedics", "linked_icd10": "S72.90XA", "pre_auth_required": False, "mandatory_investigations": ["Pre-op & Post-op X-Ray Femur", "Implant Stickers"]},
    {"package_code": "OR012", "procedure_code": "OR012B", "package_name": "Fracture Fixation", "procedure_name": "Closed Reduction Internal Fixation Tibia Interlocking", "price": 25000.0, "ceiling_inr": 25000.0, "speciality": "Orthopaedics", "linked_icd10": "S82.90XA", "pre_auth_required": False, "mandatory_investigations": ["Pre-op & Post-op X-Ray Tibia", "Implant Stickers"]},

    # Cardiology & Cardio-Thoracic Surgery
    {"package_code": "MC001", "procedure_code": "MC001A", "package_name": "Coronary Angiography", "procedure_name": "Diagnostic Coronary Angiography (CAG)", "price": 11000.0, "ceiling_inr": 11000.0, "speciality": "Cardiology", "linked_icd10": "I25.10", "pre_auth_required": False, "mandatory_investigations": ["ECG", "CAG CD / Cine Loops", "Echo Report"]},
    {"package_code": "MC002", "procedure_code": "MC002A", "package_name": "Coronary Angioplasty (PTCA)", "procedure_name": "PTCA with Single Drug-Eluting Stent (DES)", "price": 65000.0, "ceiling_inr": 65000.0, "speciality": "Cardiology", "linked_icd10": "I25.10", "pre_auth_required": True, "mandatory_investigations": ["Angiography CD", "Stent Invoice with Barcode", "Pre & Post PTCA Cine Loops"]},
    {"package_code": "MC002", "procedure_code": "MC002B", "package_name": "Coronary Angioplasty (PTCA)", "procedure_name": "PTCA with Two Drug-Eluting Stents", "price": 90000.0, "ceiling_inr": 90000.0, "speciality": "Cardiology", "linked_icd10": "I25.10", "pre_auth_required": True, "mandatory_investigations": ["Angiography CD", "Two Stent Invoices with Barcodes", "Post PTCA Cine Loops"]},
    {"package_code": "CT001", "procedure_code": "CT001A", "package_name": "CABG", "procedure_name": "Coronary Artery Bypass Graft (CABG) - On Pump / Off Pump", "price": 135000.0, "ceiling_inr": 135000.0, "speciality": "Cardiovascular Thoracic Surgery", "linked_icd10": "I25.10", "pre_auth_required": True, "mandatory_investigations": ["CAG Report & CD", "Echo Report", "Perfusion / OT Notes"]},
    {"package_code": "CT003", "procedure_code": "CT003A", "package_name": "Heart Valve Replacement", "procedure_name": "Mitral Valve Replacement (Mechanical/Bioprosthetic)", "price": 140000.0, "ceiling_inr": 140000.0, "speciality": "Cardiovascular Thoracic Surgery", "linked_icd10": "I05.0", "pre_auth_required": True, "mandatory_investigations": ["Echo Report with Valve Area", "Implant Valve Invoice and Outer Box Barcode"]},

    # Obstetrics & Gynaecology
    {"package_code": "OG001", "procedure_code": "OG001A", "package_name": "Delivery Care", "procedure_name": "Normal Delivery (Spontaneous Vaginal Delivery)", "price": 9000.0, "ceiling_inr": 9000.0, "speciality": "Obstetrics & Gynaecology", "linked_icd10": "O80", "pre_auth_required": False, "mandatory_investigations": ["Partograph", "Birth Certificate Copy", "ANC Card"]},
    {"package_code": "OG001", "procedure_code": "OG001B", "package_name": "Delivery Care", "procedure_name": "Caesarean Section (Lower Segment C-Section)", "price": 18000.0, "ceiling_inr": 18000.0, "speciality": "Obstetrics & Gynaecology", "linked_icd10": "O82", "pre_auth_required": False, "mandatory_investigations": ["USG Obstetric", "Clinical Indication Notes", "Birth Certificate"]},
    {"package_code": "OG005", "procedure_code": "OG005A", "package_name": "Hysterectomy", "procedure_name": "Total Abdominal Hysterectomy with BSO", "price": 28000.0, "ceiling_inr": 28000.0, "speciality": "Obstetrics & Gynaecology", "linked_icd10": "D25.9", "pre_auth_required": True, "mandatory_investigations": ["USG Pelvis", "Endometrial Biopsy / Pap Smear", "Histopathology Report"]},
    {"package_code": "OG005", "procedure_code": "OG005B", "package_name": "Hysterectomy", "procedure_name": "Total Laparoscopic Hysterectomy (TLH)", "price": 36000.0, "ceiling_inr": 36000.0, "speciality": "Obstetrics & Gynaecology", "linked_icd10": "D25.9", "pre_auth_required": True, "mandatory_investigations": ["USG Pelvis", "Endometrial Biopsy / Pap Smear", "Histopathology Report"]},

    # Medical Oncology & Radiation Oncology
    {"package_code": "MO001", "procedure_code": "MO001A", "package_name": "Chemotherapy", "procedure_name": "Chemotherapy Daycare - Single Drug Regimen", "price": 6000.0, "ceiling_inr": 6000.0, "speciality": "Medical Oncology", "linked_icd10": "C50.919", "pre_auth_required": False, "mandatory_investigations": ["Biopsy / IHC Report", "Medical Oncologist Prescription"]},
    {"package_code": "MO001", "procedure_code": "MO001B", "package_name": "Chemotherapy", "procedure_name": "Chemotherapy Multi-Drug Intensive Regimen", "price": 16000.0, "ceiling_inr": 16000.0, "speciality": "Medical Oncology", "linked_icd10": "C50.919", "pre_auth_required": True, "mandatory_investigations": ["Biopsy / IHC Report", "Chemo Protocol Chart", "Empty Vial Photographs"]},
    {"package_code": "RO001", "procedure_code": "RO001A", "package_name": "Radiotherapy", "procedure_name": "Intensity Modulated Radiation Therapy (IMRT) per session", "price": 45000.0, "ceiling_inr": 45000.0, "speciality": "Radiation Oncology", "linked_icd10": "C50.919", "pre_auth_required": True, "mandatory_investigations": ["Histopathology Confirmation", "RT Simulation Plan Sheet"]},

    # General Medicine & Critical Care
    {"package_code": "MM001", "procedure_code": "MM001A", "package_name": "Infectious Disease Management", "procedure_name": "Severe Dengue / Acute Febrile Illness Inpatient Ward (per day)", "price": 2500.0, "ceiling_inr": 2500.0, "speciality": "General Medicine", "linked_icd10": "A90", "pre_auth_required": False, "mandatory_investigations": ["Dengue NS1 / IgM Positive Report", "Daily Platelet Count Chart"]},
    {"package_code": "MM002", "procedure_code": "MM002A", "package_name": "Critical Care Unit", "procedure_name": "ICU with Ventilator Support Care Management (per day)", "price": 9000.0, "ceiling_inr": 9000.0, "speciality": "Critical Care", "linked_icd10": "J96.00", "pre_auth_required": True, "mandatory_investigations": ["ABG Report", "Ventilator Flowsheet Chart", "Bedside Clinical Photo"]},
    {"package_code": "MM002", "procedure_code": "MM002B", "package_name": "Critical Care Unit", "procedure_name": "ICU without Ventilator Support Care Management (per day)", "price": 5500.0, "ceiling_inr": 5500.0, "speciality": "Critical Care", "linked_icd10": "J96.00", "pre_auth_required": False, "mandatory_investigations": ["ICU Admission Notes", "Vitals Monitoring Flowsheet"]},
    {"package_code": "MM003", "procedure_code": "MM003A", "package_name": "Dialysis", "procedure_name": "Hemodialysis Session for Acute/Chronic Renal Failure", "price": 2000.0, "ceiling_inr": 2000.0, "speciality": "Nephrology", "linked_icd10": "N18.6", "pre_auth_required": False, "mandatory_investigations": ["Serum Creatinine / Urea Report", "Dialysis Record Sheet"]},

    # Paediatrics
    {"package_code": "PD001", "procedure_code": "PD001A", "package_name": "Neonatal Care", "procedure_name": "SNCU Level-II Care for Low Birth Weight / Preterm", "price": 4500.0, "ceiling_inr": 4500.0, "speciality": "Paediatrics", "linked_icd10": "P07.30", "pre_auth_required": False, "mandatory_investigations": ["Birth Weight Record", "Neonatal Admission Assessment"]},
    {"package_code": "PD002", "procedure_code": "PD002A", "package_name": "Neonatal Care", "procedure_name": "NICU Level-III Advanced Care with Mechanical Ventilation", "price": 10500.0, "ceiling_inr": 10500.0, "speciality": "Paediatrics", "linked_icd10": "P22.0", "pre_auth_required": True, "mandatory_investigations": ["ABG Analysis", "Chest X-Ray", "NICU Ventilator Log"]}
]

os.makedirs("data", exist_ok=True)
out_path = os.path.join("data", "master_pmjay_tariffs.json")
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(TARIFF_DATA, f, indent=2)

print(f"Successfully generated {out_path} with complete PMJAY schema including mandatory_investigations.")
