"""
Stage 2-4: Dense Vector Embeddings -> Similarity Search -> Exact Registry
Verification.

`SemanticRetriever` embeds every (concept + synonym) string in the ICD-10
registry once, then at query time embeds the extracted clinical phrase and
returns the closest registry entries by cosine similarity. Because the
returned code is always looked up by exact key from the original registry
dict (never generated by a model), a hallucinated / non-existent code is
structurally impossible - the worst case is a *wrong but real* code.

Embedding backend:
  - Uses `sentence-transformers` (all-MiniLM-L6-v2) if it is installed and
    a model can be loaded.
  - Otherwise falls back automatically to a TF-IDF + cosine-similarity
    vectorizer (scikit-learn), which needs no network access or model
    download and still gives solid results on this vocabulary size.

Swap EMBEDDING_BACKEND to force one or the other.
"""

import json
import os
from dataclasses import dataclass
from typing import List, Optional

import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

EMBEDDING_BACKEND = "auto"  # "auto" | "sentence-transformers" | "tfidf"


@dataclass
class RetrievalMatch:
    concept_name: str
    icd10_code: str
    snomed_id: str
    matched_text: str
    confidence: float


class _TfidfEmbedder:
    """Offline fallback embedder - no model download required."""

    name = "tfidf"

    def __init__(self, corpus: List[str]):
        self.vectorizer = TfidfVectorizer(ngram_range=(1, 2), analyzer="word")
        self.matrix = self.vectorizer.fit_transform(corpus)

    def embed_query(self, text: str):
        return self.vectorizer.transform([text])

    def similarity(self, query_vec, index: int) -> float:
        return float(cosine_similarity(query_vec, self.matrix[index]).ravel()[0])

    def similarities(self, query_vec) -> np.ndarray:
        return cosine_similarity(query_vec, self.matrix).ravel()


class _SentenceTransformerEmbedder:
    """Preferred embedder when sentence-transformers + a model are available."""

    name = "sentence-transformers"

    def __init__(self, corpus: List[str], model_name: str = "all-MiniLM-L6-v2"):
        from sentence_transformers import SentenceTransformer  # noqa: local import
        self.model = SentenceTransformer(model_name)
        self.matrix = self.model.encode(corpus, normalize_embeddings=True)

    def embed_query(self, text: str):
        return self.model.encode([text], normalize_embeddings=True)

    def similarities(self, query_vec) -> np.ndarray:
        return cosine_similarity(query_vec, self.matrix).ravel()


class SemanticRetriever:
    def __init__(self, registry_path: str, backend: str = EMBEDDING_BACKEND):
        with open(registry_path, "r") as f:
            self.registry: List[dict] = json.load(f)

        # Build one searchable text string per (entry, synonym) pair so a
        # vernacular phrase can match a specific synonym, while we always
        # resolve back to the parent registry entry for the exact code.
        self._corpus: List[str] = []
        self._corpus_owner: List[int] = []  # index into self.registry
        for i, entry in enumerate(self.registry):
            texts = [entry["concept_name"], entry.get("description", "")] + \
                    entry.get("synonyms", [])
            for t in texts:
                if t:
                    self._corpus.append(t.lower())
                    self._corpus_owner.append(i)

        self.embedder = self._build_embedder(backend)

    def _build_embedder(self, backend: str):
        if backend in ("sentence-transformers", "auto"):
            try:
                return _SentenceTransformerEmbedder(self._corpus)
            except Exception:
                if backend == "sentence-transformers":
                    raise
                # fall through to TF-IDF on any failure (not installed,
                # no network to download weights, etc.)
        return _TfidfEmbedder(self._corpus)

    def query(self, phrase: str, top_k: int = 3,
              min_confidence: float = 0.0) -> List[RetrievalMatch]:
        """
        Return up to `top_k` best-matching registry entries for `phrase`,
        each score being cosine similarity of the query against the best
        matching synonym/description text for that entry (de-duplicated by
        entry so the same ICD-10 concept isn't returned twice).
        """
        query_vec = self.embedder.embed_query(phrase.lower())
        sims = self.embedder.similarities(query_vec)

        best_per_entry = {}
        for corpus_idx, sim in enumerate(sims):
            entry_idx = self._corpus_owner[corpus_idx]
            if entry_idx not in best_per_entry or sim > best_per_entry[entry_idx][0]:
                best_per_entry[entry_idx] = (sim, corpus_idx)

        ranked = sorted(best_per_entry.items(), key=lambda kv: kv[1][0], reverse=True)

        matches: List[RetrievalMatch] = []
        for entry_idx, (sim, corpus_idx) in ranked[:top_k]:
            if sim < min_confidence:
                continue
            # Exact Registry Verification: pull the record by its real key,
            # never synthesize a code from the model output.
            entry = self.registry[entry_idx]
            matches.append(RetrievalMatch(
                concept_name=entry["concept_name"],
                icd10_code=entry["icd10_code"],
                snomed_id=entry["snomed_id"],
                matched_text=self._corpus[corpus_idx],
                confidence=round(sim, 4),
            ))
        return matches

    def best_match(self, phrase: str) -> Optional[RetrievalMatch]:
        matches = self.query(phrase, top_k=1)
        return matches[0] if matches else None


if __name__ == "__main__":
    here = os.path.dirname(os.path.abspath(__file__))
    retriever = SemanticRetriever(os.path.join(here, "data", "master_icd10_registry.json"))
    print(f"Embedding backend: {retriever.embedder.name}")
    for phrase in ["watery stools and dehydration", "high fever with body ache",
                   "sugar problm", "chronic cough with wt loss"]:
        m = retriever.best_match(phrase)
        print(f"{phrase!r} -> {m}")
