from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, field_validator

from app.schemas.common import AccessDecision, ExecutionStatus, RequesterIdentity


class EncounterType(str, Enum):
    OPD = "OPD"
    EMERGENCY = "EMERGENCY"

class EncounterRequest(BaseModel):
    encounter_id: str = Field(..., min_length=1, description="Unique encounter identifier generated by Java.")
    abha_id: str = Field(
        ...,
        min_length=1,
        description="National Indian health ID (e.g., 91-XXXX-XXXX-XXXX).",
        examples=["91-1234-5678-9012"],
    )
    requester: RequesterIdentity
    encounter_type: EncounterType = Field(..., description='Either "OPD" or "EMERGENCY".')
    raw_narrative: str = Field(..., min_length=1, description="Doctor notes or transcript of the consultation.")
    s3_audio_url: Optional[str] = Field(
        default=None, description="S3 URI if an audio recording was uploaded to Java."
    )

    @field_validator("raw_narrative")
    @classmethod
    def narrative_must_not_be_blank(cls, value: str) -> str:
        if not value.strip():
            raise ValueError("raw_narrative must not be empty or whitespace-only")
        return value

class Diagnosis(BaseModel):
    clinical_concept: str
    icd10_code: str
    snomed_id: str
    display: str


class EncounterResponse(BaseModel):
    status: ExecutionStatus
    access_decision: AccessDecision
    diagnoses: List[Diagnosis] = Field(default_factory=list)
    suggested_package_code: str
    fhir_bundle: Dict[str, Any]
